account: ${COSMOS_ACCOUNT}  # Set via environment variable or Key Vault
containers:
  policy_enrichment:
    database: insurance
    container: policy-enrichment
    partition_key: /policyId
  customer_risk_profiles:
    database: insurance
    container: customer-risk-profiles
    partition_key: /customerId
