workspace:
  name: Insurance-Prod
  lakehouses:
    bronze: lh_bronze
    silver: lh_silver
    gold: lh_gold
cosmos:
  connection_string_secret: kv-prod-cosmos-conn
kql:
  database: kql_insurance_realtime_prod
