# Silver Layer Schema Contracts

silver_policies:
  schema:
    policy_id: string
    customer_id: string
    product_type: string
    premium: double
    start_date: string
    end_date: string
    status: string
    ingestion_timestamp: timestamp
    effective_from: timestamp
    effective_to: timestamp
    is_current: boolean
  required_columns:
    - policy_id
    - customer_id
    - premium
    - effective_from
    - is_current

silver_claims:
  schema:
    claim_id: string
    policy_id: string
    claim_date: string
    claim_amount: double
    claim_status: string
    claim_type: string
    ingestion_timestamp: timestamp
    effective_from: timestamp
    effective_to: timestamp
    is_current: boolean
  required_columns:
    - claim_id
    - policy_id
    - claim_amount
    - effective_from
    - is_current

silver_customers:
  schema:
    customer_id: string
    name: string
    age: int
    gender: string
    location: string
    join_date: string
    ingestion_timestamp: timestamp
    effective_from: timestamp
    effective_to: timestamp
    is_current: boolean
  required_columns:
    - customer_id
    - name
    - effective_from
    - is_current

silver_policies_enriched:
  schema:
    policy_id: string
    customer_id: string
    product_type: string
    premium: double
    risk_score: int
    underwriting_flags: string
    external_rating: string
    ingestion_timestamp: timestamp
    ingestion_date: string
    effective_from: timestamp
    effective_to: timestamp
    is_current: boolean
  required_columns:
    - policy_id
    - customer_id
    - effective_from
    - is_current
