# Bronze Layer Schema Contracts

bronze_policies:
  schema:
    policy_id: string
    customer_id: string
    product_type: string
    premium: double
    start_date: string
    end_date: string
    status: string
    ingestion_timestamp: timestamp
    ingestion_date: string
    source_system: string
  required_columns:
    - policy_id
    - customer_id
    - premium
    - ingestion_timestamp

bronze_claims:
  schema:
    claim_id: string
    policy_id: string
    claim_date: string
    claim_amount: double
    claim_status: string
    claim_type: string
    ingestion_timestamp: timestamp
    ingestion_date: string
    source_system: string
  required_columns:
    - claim_id
    - policy_id
    - claim_amount
    - ingestion_timestamp

bronze_customers:
  schema:
    customer_id: string
    name: string
    age: int
    gender: string
    location: string
    join_date: string
    ingestion_timestamp: timestamp
    ingestion_date: string
    source_system: string
  required_columns:
    - customer_id
    - name
    - ingestion_timestamp

bronze_agents:
  schema:
    agent_id: string
    name: string
    region: string
    performance_rating: double
    ingestion_timestamp: timestamp
    ingestion_date: string
    source_system: string
  required_columns:
    - agent_id
    - name
    - ingestion_timestamp
