# Silver Layer: Policies Schema Contract
# Defines expected types after Bronze to Silver transformation
# Type casting enforced in Silver notebooks based on this schema

table_name: silver_policies
layer: silver
source_table: bronze_policies

# Business columns with enforced types
business_columns:
  - name: policy_id
    type: string
    nullable: false
    
  - name: customer_id
    type: string
    nullable: false
    
  - name: product_type
    type: string
    nullable: true
    transformation: upper_trim
    
  - name: premium
    type: double
    nullable: false
    validation:
      - rule: greater_than
        value: 0
    
  - name: status
    type: string
    nullable: true
    transformation: upper_trim
    
  - name: start_date
    type: date
    nullable: true

# SCD Type 2 columns (auto-added)
scd_columns:
  - effective_from
  - effective_to
  - is_current

# Processing metadata
metadata_columns:
  - processed_timestamp
  - ingestion_timestamp
  - source_system
  - process_id
