trigger:
  branches:
    include:
      - main
      - develop

pr:
  branches:
    include:
      - main
      - develop

jobs:
  - job: ci
    displayName: CI Validation
    pool:
      vmImage: ubuntu-latest
    steps:
      - script: echo "Run lint, unit tests, config validation"
        displayName: Placeholder validation
