trigger:
  branches:
    include:
      - main

stages:
  - stage: Deploy_Fabric
    displayName: Deploy to Microsoft Fabric
    jobs:
      - deployment: deploy_fabric
        displayName: Deploy Workspace
        environment: fabric-insurance
        pool:
          vmImage: ubuntu-latest
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                
                - task: UsePythonVersion@0
                  inputs:
                    versionSpec: '3.9'
                  displayName: 'Use Python 3.9'
                
                - script: |
                    pip install -r requirements.txt
                    pip install pyyaml requests
                  displayName: 'Install dependencies'
                
                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: '$(azureServiceConnection)'
                    KeyVaultName: '$(keyVaultName)'
                    SecretsFilter: '*'
                  displayName: 'Fetch secrets from Key Vault'
                
                - script: |
                    python framework/scripts/deploy_to_fabric.py
                  displayName: 'Deploy to Fabric Workspace'
                  env:
                    FABRIC_TOKEN: $(fabric_token)
                    COSMOS_ENDPOINT: $(cosmos_endpoint)
                    COSMOS_KEY: $(cosmos_key)
                
                - script: |
                  echo "Deployment summary:"
                  echo "- Workspace: Insurance-ML-Platform"
                  echo "- Components: Lakehouses (3), KQL DB (1), Pipelines (2)"
                  echo "- Purview Integration: ENABLED (auto-discovery)"
                  echo "- Status: SUCCESS ✓"
                  displayName: 'Deployment summary'
                
                - script: |
                    echo "📊 Purview Hub Configuration:"
                    echo "  ✓ Data Catalog: Auto-enabled in Fabric"
                    echo "  ✓ Lineage Tracking: Enabled (table→table, notebook→table)"
                    echo "  ✓ Metadata Sync: Schema contracts synced"
                    echo "  📍 Access Purview: Fabric Workspace → Purview Hub"
                    echo ""
                    echo "⚠️  Note: Custom DQ monitoring dashboards are RETAINED"
                    echo "   Reason: Purview does not support custom DQ rules/thresholds"
                  displayName: 'Purview Integration Status'
