name: bronze_policies
description: Schema contract for Bronze policies table

schema:
  policy_id: string
  customer_id: string
  agent_id: string
  product_type: string
  premium: double
  coverage_amount: double
  start_date: timestamp
  end_date: timestamp
  status: string
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string

required_columns:
  - policy_id
  - customer_id
  - premium
  - start_date
  - ingestion_timestamp

validation_rules:
  - column: premium
    min: 0
    max: 1000000
  - column: coverage_amount
    min: 0
    max: 100000000
