name: bronze_claims
description: Schema contract for Bronze claims table

schema:
  claim_id: string
  policy_id: string
  customer_id: string
  claim_date: timestamp
  claim_amount: double
  claim_status: string
  claim_type: string
  description: string
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string

required_columns:
  - claim_id
  - policy_id
  - claim_date
  - claim_amount
  - ingestion_timestamp

validation_rules:
  - column: claim_amount
    min: 0
    max: 10000000
  - column: claim_status
    allowed_values: ["SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "PAID"]
