name: bronze_realtime_events
description: Schema contract for Bronze real-time streaming events (dual-sink from Eventstream)

schema:
  event_time: timestamp
  claim_id: string
  policy_id: string
  amount: double
  status: string
  event_type: string
  delta_ingestion_timestamp: timestamp
  ingestion_date: string

required_columns:
  - event_time
  - claim_id
  - policy_id
  - amount
  - delta_ingestion_timestamp

validation_rules:
  - column: amount
    min: 0
    max: 10000000
  - column: status
    allowed_values: ["SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "PAID", "URGENT"]
  - column: event_type
    allowed_values: ["CLAIM_SUBMISSION", "CLAIM_UPDATE", "CLAIM_APPROVAL", "CLAIM_PAYMENT"]
