name: gold_streaming_features
description: Schema contract for Gold streaming features (real-time aggregations)

schema:
  policy_id: string
  claims_submitted_last_1hr: int
  amount_sum_1hr: double
  avg_claim_amount_1hr: double
  claims_submitted_last_24hr: int
  amount_sum_24hr: double
  avg_claim_amount_24hr: double
  feature_timestamp: timestamp
  load_timestamp: timestamp

required_columns:
  - policy_id
  - feature_timestamp
  - load_timestamp

validation_rules:
  - column: claims_submitted_last_1hr
    min: 0
    max: 1000
  - column: claims_submitted_last_24hr
    min: 0
    max: 10000
  - column: amount_sum_1hr
    min: 0
  - column: amount_sum_24hr
    min: 0
