name: gold_claims_features
description: Schema contract for Gold claims features table

schema:
  customer_id: string
  claim_amount_sum_30d: double
  claim_amount_avg_30d: double
  claim_amount_max_30d: double
  claim_amount_count_30d: long
  claims_count_30d: long
  claim_amount_sum_90d: double
  claim_amount_avg_90d: double
  claim_amount_max_90d: double
  claim_amount_count_90d: long
  claims_count_90d: long
  claim_amount_sum_365d: double
  claim_amount_avg_365d: double
  claim_amount_max_365d: double
  claim_amount_count_365d: long
  claims_count_365d: long
  days_since_last_claim: int
  feature_timestamp: timestamp
  load_timestamp: timestamp

required_columns:
  - customer_id
  - feature_timestamp
  - load_timestamp

validation_rules:
  - column: claim_amount_sum_30d
    min: 0
    max: 10000000
  - column: claim_amount_sum_90d
    min: 0
    max: 30000000
  - column: claim_amount_sum_365d
    min: 0
    max: 100000000
  - column: days_since_last_claim
    min: 0
    max: 36500
