name: gold_risk_features
description: Schema contract for Gold risk assessment features

schema:
  customer_id: string
  policy_id: string
  overall_risk_score: double
  risk_score: double
  claims_count_365d: int
  claim_amount_sum_365d: double
  claim_amount_max_365d: double
  high_value_claim_ratio: double
  feature_timestamp: timestamp
  load_timestamp: timestamp

required_columns:
  - customer_id
  - policy_id
  - overall_risk_score
  - feature_timestamp

validation_rules:
  - column: overall_risk_score
    min: 0.0
    max: 100.0
  - column: risk_score
    min: 0.0
    max: 100.0
  - column: high_value_claim_ratio
    min: 0.0
    max: 1.0
