name: silver_realtime_claims
description: Schema contract for Silver real-time claims (validated and deduplicated streaming events)

schema:
  event_time: timestamp
  claim_id: string
  policy_id: string
  customer_id: string
  amount: double
  status: string
  event_type: string
  ingestion_date: string
  processing_timestamp: timestamp

required_columns:
  - event_time
  - claim_id
  - policy_id
  - amount
  - processing_timestamp

validation_rules:
  - column: amount
    min: 0
    max: 10000000
  - column: status
    allowed_values: ["SUBMITTED", "UNDER_REVIEW", "APPROVED", "REJECTED", "PAID", "URGENT"]
