name: silver_claims
description: Schema contract for Silver claims table with data quality rules

schema:
  claim_id: string
  policy_id: string
  customer_id: string
  claim_date: timestamp
  claim_amount: double
  claim_status: string
  claim_type: string
  description: string
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string
  effective_from: timestamp
  effective_to: timestamp
  is_current: boolean

required_columns:
  - claim_id
  - policy_id
  - claim_date
  - claim_amount
  - effective_from
  - is_current

validation_rules:
  - column: claim_amount
    min: 0
    max: 10000000
  - column: claim_status
    allowed_values: ["SUBMITTED", "UNDER_REVIEW", "PENDING", "APPROVED", "REJECTED", "PAID"]
