name: silver_customers
description: Schema contract for Silver customers table with SCD2

schema:
  customer_id: string
  name: string
  age: int
  gender: string
  email: string
  phone: string
  location: string
  join_date: timestamp
  customer_type: string
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string
  effective_from: timestamp
  effective_to: timestamp
  is_current: boolean

required_columns:
  - customer_id
  - name
  - join_date
  - effective_from
  - is_current

validation_rules:
  - column: age
    min: 18
    max: 120
  - column: gender
    allowed_values: ["M", "F", "OTHER"]
