name: silver_policies_enriched
description: Schema contract for Silver policies enriched with Cosmos DB data

schema:
  policy_id: string
  customer_id: string
  agent_id: string
  product_type: string
  premium: double
  coverage_amount: double
  start_date: timestamp
  end_date: timestamp
  status: string
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string
  effective_from: timestamp
  effective_to: timestamp
  is_current: boolean
  # Cosmos DB enrichment fields
  risk_score: double
  underwriting_flags: string
  external_rating: string

required_columns:
  - policy_id
  - customer_id
  - premium
  - start_date
  - effective_from
  - is_current

validation_rules:
  - column: premium
    min: 0
    max: 1000000
  - column: risk_score
    min: 0
    max: 100
  - column: status
    allowed_values: ["ACTIVE", "EXPIRED", "CANCELLED", "PENDING"]
