name: silver_agents
description: Schema contract for Silver agents table with SCD2

schema:
  agent_id: string
  name: string
  agent_type: string
  region: string
  status: string
  performance_rating: double
  joined_date: timestamp
  ingestion_timestamp: timestamp
  ingestion_date: string
  source_system: string
  effective_from: timestamp
  effective_to: timestamp
  is_current: boolean

required_columns:
  - agent_id
  - name
  - region
  - effective_from
  - is_current

validation_rules:
  - column: performance_rating
    min: 0.0
    max: 5.0
  - column: status
    allowed_values: ["ACTIVE", "INACTIVE", "ON_LEAVE"]
