# Bronze Layer: Claims Schema Contract
# Simplified version - demo purposes only

table_name: bronze_claims
layer: bronze

required_columns:
  - name: claim_id
    type: string
    nullable: false
    
  - name: policy_id
    type: string
    nullable: false
    
  - name: claim_amount
    type: double
    nullable: false
    
  - name: claim_date
    type: date
    nullable: true
    
  - name: claim_status
    type: string
    nullable: true
    
  - name: claim_type
    type: string
    nullable: true

metadata_columns:
  - ingestion_timestamp
  - ingestion_date
  - source_system
