# Simplified Fabric Workspace Configuration
# For demonstration purposes

workspace:
  name: Insurance-ML-Platform
  id: fabric-workspace-insurance-id  # Replace with actual workspace ID
  
lakehouses:
  bronze: lh_bronze
  silver: lh_silver
  gold: lh_gold

fabric_capacity:
  name: Fabric-Capacity-F64  # Adjust based on your capacity
  region: East US

# Git Integration Settings (recommended deployment method)
git_integration:
  enabled: true
  provider: AzureDevOps  # or GitHub
  repository: Insurance-ML-Data-Platform
  branch: main
